export const authConstants = {
  REGISTER_IN_PROCESS: 'REGISTER_IN_PROCESS',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  LOGIN_IN_PROCESS: 'LOGIN_IN_PROCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  CHANGE_PASSWORD_IN_PROCESS: 'CHANGE_PASSWORD_IN_PROCESS',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  LOGOUT: 'LOGOUT'
};
