export const todosConstants = {
  GET_TODOS_IN_PROCESS: 'GET_TODOS_IN_PROCESS',
  GET_TODOS_SUCCESS: 'GET_TODOS_SUCCESS',
  GET_TODOS_FAILURE: 'GET_TODOS_FAILURE',

  CREATE_TODO_IN_PROCESS: 'CREATE_TODO_IN_PROCESS',
  CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
  CREATE_TODO_FAILURE: 'CREATE_TODO_FAILURE'
};
